# The URL the site will be built for
base_url = "https://gitrus.github.io"
title = "gitrus pages"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
taxonomies = [{ name = "tags" }]

theme = "apollo"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# some
menu = [
    { name = "Blog", url = "/blog", weight = 1 },
    { name = "Middle Dev Insights", url = "/middle-dev", weight = 2 },
]

fancy_code = true
dynamic_note = true

theme = "toggle"

socials = [
    { name = "github", url = "https://github.com/gitrus/", icon = "github" },
]

[extra.analytics]
enabled = false
